name: ⚡ 性能问题
description: 报告性能相关的问题或建议性能优化
title: "[Performance]: "
labels: ["performance", "需要分类"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        感谢你报告性能问题！请提供详细的性能指标和场景，这将帮助我们诊断和优化。

  - type: checkboxes
    id: prerequisites
    attributes:
      label: 前置检查
      options:
        - label: 我已经搜索过现有的性能相关 Issues
          required: true
        - label: 我已经确认这不是上游平台本身的性能问题
          required: true

  - type: dropdown
    id: issue_type
    attributes:
      label: 问题类型
      description: 选择性能问题的类型
      options:
        - 响应时间过长
        - 超时错误
        - 高延迟
        - 带宽限制
        - 缓存未命中
        - 内存使用过高
        - 并发性能问题
        - 其他
    validations:
      required: true

  - type: dropdown
    id: affected_platform
    attributes:
      label: 受影响的平台
      description: 哪个平台的性能出现问题？
      options:
        - GitHub
        - GitLab
        - npm
        - PyPI
        - Docker Hub
        - crates.io
        - Maven Central
        - Homebrew
        - Jenkins
        - OpenAI API
        - Anthropic API
        - 多个平台
        - 所有平台
    validations:
      required: true

  - type: dropdown
    id: operation_type
    attributes:
      label: 操作类型
      description: 什么类型的操作性能有问题？
      options:
        - Git 克隆
        - Git 拉取
        - Git LFS 下载
        - Docker 镜像拉取
        - 包下载
        - AI API 请求
        - 元数据获取
        - 其他
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 详细描述性能问题
      placeholder: |
        在执行...操作时，性能明显低于预期...
        相比直接访问上游，速度慢了...
    validations:
      required: true

  - type: textarea
    id: metrics
    attributes:
      label: 性能指标
      description: 提供具体的性能数据
      placeholder: |
        - 响应时间: XX ms (预期 < YY ms)
        - 下载速度: XX KB/s (上游直连: YY KB/s)
        - 首字节时间 (TTFB): XX ms
        - 总耗时: XX 秒
        - X-Performance-Metrics 头信息: {...}
      render: markdown
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 重现步骤
      description: 提供详细的重现步骤和测试命令
      render: shell
      placeholder: |
        # 测试命令
        time git clone https://your-xget-instance/gh/user/repo

        # 或使用 curl 测试
        curl -w "@curl-format.txt" -o /dev/null https://your-xget-instance/...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 环境信息
      description: 提供详细的环境信息
      value: |
        - Xget 部署方式: [Cloudflare Workers / 自托管 / ...]
        - Xget 区域: [US/EU/ASIA/...]
        - 客户端位置: [国家/地区]
        - 网络环境: [家庭宽带 / 公司网络 / VPS / ...]
        - ISP:
        - 客户端工具版本:
        - 操作系统:
    validations:
      required: true

  - type: textarea
    id: resource_size
    attributes:
      label: 资源规模
      description: 描述涉及的资源大小
      placeholder: |
        - 存储库大小: XX MB
        - 文件数量: XX 个
        - 单个文件大小: XX MB
        - Docker 镜像大小: XX GB
        - 镜像层数: XX 层

  - type: textarea
    id: comparison
    attributes:
      label: 性能对比
      description: 对比 Xget 与直接访问上游的性能差异
      placeholder: |
        | 操作 | 通过 Xget | 直接访问上游 | 差异 |
        |------|-----------|--------------|------|
        | 克隆 | 30s       | 10s          | +200% |
        | 拉取 | 5s        | 2s           | +150% |
      render: markdown

  - type: textarea
    id: cache_info
    attributes:
      label: 缓存信息
      description: 检查响应的缓存相关 Header
      placeholder: |
        - CF-Cache-Status:
        - X-Cache-Status:
        - Age:
        - Cache-Control:
      render: markdown

  - type: textarea
    id: network_trace
    attributes:
      label: 网络追踪
      description: 如果可能，提供网络追踪信息（如 curl -v 输出的关键部分）
      render: shell
      placeholder: |
        * Connected to your-xget-instance (...)
        * TLS handshake...
        < HTTP/2 200
        < x-performance-metrics: {...}

  - type: dropdown
    id: frequency
    attributes:
      label: 问题频率
      description: 这个性能问题多久发生一次？
      options:
        - 每次都发生
        - 经常发生 (>50%)
        - 偶尔发生 (10-50%)
        - 很少发生 (<10%)
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: 影响程度
      description: 这个性能问题的影响有多大？
      options:
        - 严重 - 完全无法使用
        - 高 - 严重影响工作效率
        - 中 - 造成明显不便
        - 低 - 轻微影响
    validations:
      required: true

  - type: textarea
    id: expected_performance
    attributes:
      label: 期望的性能
      description: 描述你期望的性能指标
      placeholder: |
        - 理想响应时间: < 100ms
        - 可接受的下载速度: > 1MB/s
        - 目标改进: 减少 50% 的延迟

  - type: textarea
    id: suggestions
    attributes:
      label: 优化建议
      description: 如果你有优化建议，请在此描述
      placeholder: |
        可能的优化方向:
        - 增加缓存时长
        - 使用流式传输
        - 优化重试策略
        - ...

  - type: textarea
    id: additional
    attributes:
      label: 附加信息
      description: 提供任何其他有助于诊断性能问题的信息
